### ISSUE TITLE
Inconsistent Cuneiform version.

### ISSUE THREAD

**Issue by stigviaene** [marcbux/hiway-chef#3]
The Cuneiform version specified in defaults.rb (2.0.1-SNAPSHOT right now) is not considered when fetching Cuneiform from github (currently 2.0.2-SNAPSHOT), leading to:

```
STDERR: cp: cannot stat ‘/tmp/cuneiform/cuneiform-dist/target/cuneiform-dist-2.0.1-SNAPSHOT/cuneiform-2.0.1-SNAPSHOT’: No such file or directory
```

**Comment by marcbux** [comment]
The Cuneiform version change from 2.0.1 to 2.0.2 caused some trouble indeed. I fixed this now and future version changes should not lead to the same error.
