### ISSUE TITLE
hiway_client.rb tries to create hdfs root folder

### ISSUE THREAD

**Issue by jimdowling** [marcbux/hiway-chef#6]
Hiway shouldnt assume that no hdfs folders exist in the system.
If hiway needs hdfs superuser privileges and yarn superuser privileges, maybe you should run commands as user node[:hdfs][:user] or node[:hadoop][:yarn][:user]. Or have hiway in group node[:hadoop][:group]. 

This code fails. It tries to create the '/' directory - which is the default basedir. 
It doesn't make sense to change owner of the root folder away from the hdfs superuser (don't know if you even can do this, tbh).
Why not just make the default for 
node[:hiway][:hiway][:hdfs][:basedir] = "/home/#{node[:hiway][:user]}"

This line is the problem:
# create hiway user directory in HDFS (if necessary) and grant read and write rights to all users in hadoop group such that both the yarn and hiway users can use the directory

hadoop_hdfs_directory "#{node[:hiway][:hiway][:hdfs][:basedir]}" do
  action :create
  owner node[:hiway][:user]
  group node[:hiway][:group]
  mode "0775"
end

**Comment by marcbux** [comment]
Thanks for the hint. Having the hiway user home directory as a place to store data makes indeed more sense. After all, things like this is what we create the hiway user for. I've changed hiway's default hdfs base directory to /user/#{node[:hiway][:user]} just now. It used to be this way before, but I changed it at some point along the way.

**Comment by jimdowling** [comment]
Btw, in the apache hadoop cookbook, and the hdfs_directory LWRP, there are two ways to create directories: (1) as the current user or (2) as superuser, who then then runs chown and chmod on the created directory to a user of your choice. You were the one who wanted me to do this. Maybe it's best to use (2) - "action: create_as_superuser"

**Comment by marcbux** [comment]
That's great news, which I was unaware of. I'll transition to create_as_superuser asap. I'd like to make sure that it doesn't break anything though. Since my testing capabilities are limited right now, it'll have to wait until I'm back from vacation. Thanks!
